theme = "bogster" # default theme

[editor]
line-number = "relative"
mouse = true
auto-format = true
bufferline = "multiple"
auto-pairs = true
cursorline = true
true-color = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator" ]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "┊" # unicode character 0x250A
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] 
space.t.d = ":theme bogster"
space.t.l = ":theme gruvbox_light"
