[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]
auto-format = true

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = [ "server" ]

[language.formatter]
command = "ruff"
args = [ "format", "--line-length", "88", "--quiet", "-" ] 

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
formatter = { command = "prettierd", args = [".md"] }
auto-format = true


[[language]]
name = "toml"
formatter = { command = "taplo", args = [ "format", "-" ] }
auto-format = true

[language-server.taplo.config]
# Workaround for nonsense of being nonfunctional outside git directories
# (https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437)
root_dir = [".git", "*.toml"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true

[[language]]
name = "clojure"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "cljfmt", args = [ "fix" ] }
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "sql"
language-servers = ["sqruff"]
formatter = { command = "sqruff", args = ["fix", "-"] }
auto-format = true

[language-server.sqruff]
command = "sqruff"
args = ["lsp"]

