[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]
auto-format = true

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = [ "server" ]

[language.formatter]
command = "ruff"
args = [ "format", "--line-length", "88", "--quiet", "-" ] 

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]

[[language]]
name = "toml"
formatter = { command = "taplo", args = [ "format", "-" ] }
auto-format = true
